[tool.poetry]
name = "tnpy"
version = "0.1.1a2"
description = "Tensor Network algorithms implemented in python."
authors = ["taolin <tanlin2013@gmail.com>"]
homepage = "https://github.com/tanlin2013/tnpy"
documentation = "https://tanlin2013.github.io/tnpy/"
readme = "README.md"
keywords = ["tensornetwork", "quantum-mechanics", "quantum-algorithms"]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
toml = "^0.10.2"
tqdm = "^4.63.0"
numpy = "1.21.6"
scipy = "1.8.0"
primme = "3.2.1"
h5py = "3.6.0"
graphviz = "0.20"
#mkl-devel = "2022.0.3"
tensornetwork = "0.4.6"
autoray = "0.2.5"
quimb = "1.3.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"
pylint = "^2.13.7"
flake8 = "^4.0.1"
mypy = "^0.942"
sphinx = "^4.5.0"
sphinx-book-theme = "^0.3.2"
m2r2 = "^0.3.2"
pandoc = "^2.1"
nbsphinx = "^0.8.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
