[tool.poetry]
name = "tnpy"
version = "0.1.0"
description = ""
authors = ["taolin <tanlin2013@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.10"
pyyaml = "^6.0"
tqdm = "^4.63.0"
numpy = "1.21.2"
scipy = "1.8.0"
h5py = "3.6.0"
graphviz = "0.20"
# mkl-devel = 2021.4.0
tensornetwork = "0.4.6"
autoray = "0.2.5"
quimb = "1.3.0"
primme = {version = "3.2.1", markers = "platform_python_implementation == 'CPython'"}

[tool.poetry.group.test.dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.6.1"

[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
flake8 = "^4.0.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^4.5.0"
sphinx-book-theme = "^0.3.2"
m2r2 = "^0.3.2"
pandoc = "^2.1"
nbsphinx = "^0.8.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
