name: docs

on:
  workflow_run:
    workflows: [ "Docker build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://tanlin2013/tnpy:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Sphinx doc
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install -r docs/requirements.txt && python setup.py install"
          build-command: "make html SPHINXOPTS='-W --keep-going -n'"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
