# Reference
# How to use make with flags
# make html SPHINXOPTS+='-W --keep-going -n'
# See this Github issue: Action fails with due to missing log file
# https://github.com/ammaraskar/sphinx-action/issues/5

name: docs

on:
  workflow_run:
    workflows: [ "Docker build" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://tanlin2013/tnpy:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Sphinx doc
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install -r docs/requirements.txt"
          build-command: "make html"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
