# https://github.com/marketplace/actions/pypi-publish

name: publish
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: docker://tanlin2013/tnpy:latest
    steps:
      - uses: actions/checkout@v3

      - name: Build package
        run: poetry build -f wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
