name: tests

on:
  workflow_run:
    workflows: [ "docker-build" ]
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: docker://tanlin2013/tnpy:latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test
        run: python -m unittest discover -s tests -p 'test_*.py'
