name: tests

on:
  workflow_run:
    workflows: [ "Docker build" ]
    types:
      - completed

env:
  IMAGE_PATH: "docker://${{ secrets.DOCKERHUB_USERNAME }}/tnpy:latest"

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.IMAGE_PATH }}
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test
        run: python -m unittest discover -s tests -p 'test_*.py'
